# Generated by Django 5.0.2 on 2024-08-02 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MillersEntrymodel',
            fields=[
                ('MILLER_TRANSPORTER_ID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('MILLER_NAME', models.CharField(blank=True, max_length=200)),
                ('ContactNo', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits')])),
                ('district', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['MILLER_TRANSPORTER_ID', 'MILLER_NAME', 'ContactNo', 'district'],
            },
        ),
    ]
