# Generated by Django 5.0.2 on 2024-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reactivation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivationmodels',
            name='Dealer_Name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
