from django.db import models

# Create your models here.
class OTRData(models.Model):
        id=models.AutoField(primary_key=True)
        MILLER_TRANSPORTER_ID=models.CharField(max_length=15,blank=True)
        MILLER_NAME=models.CharField(max_length=150,blank=True)
        district=models.CharField(max_length=200,blank=True)
        MillerContactNo=models.CharField(max_length=15,blank=True)
        Dealer_Name=models.CharField(max_length=150,blank=True)
        Entity_id=models.CharField(max_length=15,blank=True)
        GPS_IMEI_NO=models.CharField(max_length=20,blank=True)
        SIM_NO=models.CharField(max_length=20,blank=True)
        Device_Name=models.CharField(max_length=150,blank=True)
        NewRenewal=models.CharField(max_length=50,blank=True)
        OTR=models.CharField(max_length=10,blank=True)
        vehicle1=models.CharField(max_length=150,blank=True)
        vehicle2=models.CharField(max_length=150,blank=True)
        vehicle3=models.CharField(max_length=150,blank=True)
        InstallationDate=models.DateField(null=True,blank=True)
        Employee_Name=models.CharField(max_length=150,blank=True)
        Device_Fault=models.CharField(max_length=150,blank=True)
        Fault_Reason=models.CharField(max_length=200,blank=True)
        Replace_DeviceIMEI_NO=models.CharField(max_length=20,blank=True)
        ExpiryDate=models.DateField(null=True,blank=True)
        extendedMonth=models.CharField(max_length=10,blank=True)
        nextExpirydate=models.DateField(null=True,blank=True)