# Generated by Django 5.0.2 on 2024-08-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deactivation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivationmodels',
            name='Entity_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
