# Generated by Django 5.0.2 on 2024-08-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deactivation', '0002_alter_deactivationmodels_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivationmodels',
            name='Dealer_Name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
