# Generated by Django 5.0.2 on 2024-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installatonmodels',
            name='Entity_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
