# Generated by Django 5.0.2 on 2024-08-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTRData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MILLER_TRANSPORTER_ID', models.CharField(blank=True, max_length=15)),
                ('MILLER_NAME', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=200)),
                ('MillerContactNo', models.CharField(blank=True, max_length=15)),
                ('Dealer_Name', models.CharField(blank=True, max_length=150)),
                ('Entity_id', models.CharField(blank=True, max_length=15)),
                ('GPS_IMEI_NO', models.CharField(blank=True, max_length=20)),
                ('SIM_NO', models.CharField(blank=True, max_length=20)),
                ('Device_Name', models.CharField(blank=True, max_length=150)),
                ('NewRenewal', models.CharField(blank=True, max_length=50)),
                ('OTR', models.CharField(blank=True, max_length=10)),
                ('vehicle1', models.CharField(blank=True, max_length=150)),
                ('vehicle2', models.CharField(blank=True, max_length=150)),
                ('vehicle3', models.CharField(blank=True, max_length=150)),
                ('InstallationDate', models.CharField(blank=True, max_length=15)),
                ('Employee_Name', models.CharField(blank=True, max_length=150)),
                ('Device_Fault', models.CharField(blank=True, max_length=150)),
                ('Fault_Reason', models.CharField(blank=True, max_length=200)),
                ('Replace_DeviceIMEI_NO', models.CharField(blank=True, max_length=20)),
                ('ExpiryDate', models.DateField(blank=True, null=True)),
                ('extendedMonth', models.CharField(blank=True, max_length=10)),
                ('nextExpirydate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
