# Generated by Django 5.0.2 on 2024-08-02 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealersmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Dealer_Name', models.CharField(max_length=200)),
                ('contactno1', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits')])),
                ('contactno2', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits')])),
                ('companyName', models.CharField(blank=True, max_length=200)),
                ('Remark', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['id', 'Dealer_Name', 'contactno1', 'contactno2', 'companyName', 'Remark'],
            },
        ),
    ]
